name: CI

on:
  push:
    branches:
      - main
      - "v*"
  pull_request:

env:
  NODE_VERSION: "16.x"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: wyvox/action-setup-pnpm@v3
        with:
          pnpm-version: 8.6.0
          node-version: "${{ env.NODE_VERSION }}"
          args: "--frozen-lockfile"
      - name: Lint
        run: pnpm lint

  test:
    name: Tests
    runs-on: ${{ matrix.os }}
    needs: lint

    strategy:
      matrix:
        os: [ubuntu-latest]
        browser: [chrome]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: wyvox/action-setup-pnpm@v3
        with:
          pnpm-version: 8.6.0
          node-version: "${{ env.NODE_VERSION }}"
          args: "--frozen-lockfile"
      - name: Run Tests
        run: pnpm test:ember --launch ${{ matrix.browser }}
        working-directory: test-app

  floating-dependencies:
    name: Floating Dependencies
    runs-on: ${{ matrix.os }}
    needs: lint

    strategy:
      matrix:
        os: [ubuntu-latest]
        browser: [chrome]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: wyvox/action-setup-pnpm@v3
        with:
          pnpm-version: 8.6.0
          node-version: "${{ env.NODE_VERSION }}"
          args: "--no-lockfile"
      - name: Run tests
        run: pnpm test:ember
        working-directory: test-app

  try-scenarios:
    name: Tests - ${{ matrix.ember-try-scenario }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-failure }}
    needs: test

    strategy:
      fail-fast: true
      matrix:
        ember-try-scenario:
          [
            ember-lts-3.28,
            ember-lts-4.4,
            ember-lts-4.8,
            ember-classic,
            ember-release,
            ember-beta,
            embroider-safe,
            embroider-optimized,
          ]
        allow-failure: [false]
        include:
          - ember-try-scenario: ember-canary
            allow-failure: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: wyvox/action-setup-pnpm@v3
        with:
          pnpm-version: 8.6.0
          node-version: "${{ env.NODE_VERSION }}"
          args: "--frozen-lockfile"
      - name: Run tests
        run: pnpm ember try:one ${{ matrix.ember-try-scenario }} --skip-cleanup
        working-directory: test-app
